### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-africa/pypsa-earth-sec#114]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-earth-sec/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-earth-sec/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

The CI is not working, there is the need to update the testing config file to adapt it to make the CI work

**Comment by energyLS** [comment]
At which point does it fail? I have added the ll wildcard to the add_biomass branch which solves one error but nonetheless the CI fails when trying to access the options (https://github.com/pypsa-meets-africa/pypsa-earth-sec/commit/b1c9706dc800defed64b8ad521c16eb5be82d4ab#diff-d838d3f5e300ee6371584a10781b96424387d2186d355c6cf601433ac3e189cbR155)

**Comment by energyLS** [comment]
I will take on this issue
