### ISSUE TITLE
Add script to create population layout

### ISSUE THREAD

**Issue by Hazem-IEG** [pypsa-meets-africa/pypsa-earth-sec#12]
This is necessary for all the different demand sector we're going to add to the model.

check: PyPSA-EUR-SEC script `"build_population_layout.py"` and `"build_clustered_population.py"`

Check add_population() function in build_shapes.py in PyPSA-africa

- [x] Create dummy data (equal distribution of population)
- [ ] Improve it using real data on population (no distinction between rural and urban?)

**Expected output:** A csv file with the population of each node divided into urban and rural

**Comment by energyLS** [comment]
I have created a script to create a simple dummy pop_layout, by simple equal distribution between nodes and urban/rural and saving the csv to resources. See commit 4d0812ea0cd45a33428a2b33a811fd405fa4b3e2 on my current branch 'add_land_transport'
is this sufficient for now? If yes, we can close the issue once we've merged the branch

**Comment by Hazem-IEG** [comment]
All the open issues depend on this one now. It think we should open the pull request and merge it back now. @energyLS if you don't have time now I can take it from here

**Comment by energyLS** [comment]
The rule to create the calculate_dummy_pop_layout is in PR #28. After the merge, it would be great if you can take it from here and  improve it using real data on population

**Comment by Hazem-IEG** [comment]
The following error rises when I try to create a population layout.
Maybe the cutout file is somehow different between PyPSA-EUR-SEC and here and that is what causes the problem?

Traceback (most recent call last):

  File ~/anaconda3/envs/pypsa-africa/lib/python3.9/site-packages/atlite/cutout.py:193 in __init__
    x = cutoutparams.pop("x")

KeyError: 'x'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File ~/projects/Github/pypsa-earth-sec/scripts/build_population_layouts.py:17 in <module>
    cutout = atlite.Cutout(snakemake.config['atlite']['cutout'])

  File ~/anaconda3/envs/pypsa-africa/lib/python3.9/site-packages/atlite/cutout.py:198 in __init__
    raise TypeError(

TypeError: Arguments 'time' and 'module' must be specified. Spatial bounds must either be passed via argument 'bounds' or 'x' and 'y'.


runfile('/home/user/projects/Github/pypsa-earth-sec/scripts/build_population_layouts.py', wdir='/home/user/projects/Github/pypsa-earth-sec/scripts')
INFO:atlite.cutout:Building new cutout /cutouts/africa-2013-era5.nc
Reloaded modules: helpers
Traceback (most recent call last):

  File ~/anaconda3/envs/pypsa-africa/lib/python3.9/site-packages/atlite/cutout.py:193 in __init__
    x = cutoutparams.pop("x")

KeyError: 'x'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File ~/projects/Github/pypsa-earth-sec/scripts/build_population_layouts.py:17 in <module>
    cutout = atlite.Cutout(snakemake.config['atlite']['cutout'])

  File ~/anaconda3/envs/pypsa-africa/lib/python3.9/site-packages/atlite/cutout.py:198 in __init__
    raise TypeError(
`
TypeError: Arguments 'time' and 'module' must be specified. Spatial bounds must either be passed via argument 'bounds' or 'x' and 'y'.`

**Comment by Hazem-IEG** [comment]
@euronion do you have ideas to why this is happening?

**Comment by Hazem-IEG** [comment]
Okay, my bad.. the path was not specified correctly. The error message misled me a bit.
