### ISSUE TITLE
Create functions to prepare data for the land transport sector

### ISSUE THREAD

**Issue by Hazem-IEG** [pypsa-meets-africa/pypsa-earth-sec#25]
Check the function `prepare_data` in PyPSA-EUR-SEC's `prepare_sector_network` 

The function creates the different parameters and process the demand data for the land transport sector as well as the heat sector. This should be dis-aggregated into two different functions and later to two different rules.

- [x] Create the function to create the land transport parameters and process the data.
- [ ] Create an issue for the heat sector data preparation function that is needed later on.

**Comment by energyLS** [comment]
I am currently working on this issue, this is also partly tackled by PR #28. I have created the script (and rule) prepare_transport_data.py which I am currently working on (in branch add_land_transport)
