### ISSUE TITLE
Create script to build temperature profiles

### ISSUE THREAD

**Issue by Hazem-IEG** [pypsa-meets-africa/pypsa-earth-sec#27]
Check `build_temperature_profiles.py` in PyPSA-EUR-SEC
This script is not only needed for the heat sector, but also for the land transport sector.

**Comment by energyLS** [comment]
For the MVP, I have just created dummy data (copying the temperature from Spain to Morocco) to resolve #25. I guess this is sufficient for the MVP. You can find the function in branch "prepare_transport_data", scripts helpers.py function create_temperature_dummy().
