### ISSUE TITLE
Investigate and implement the fischer-tropsch technology representation

### ISSUE THREAD

**Issue by Hazem-IEG** [pypsa-meets-africa/pypsa-earth-sec#36]

**Comment by energyLS** [comment]
What excactly is required here @Hazem-IEG ? I've been looking into it, we implement Fischer Tropsch in https://github.com/pypsa-meets-africa/pypsa-earth-sec/blob/main/scripts/prepare_sector_network.py#L130. It links the nodal H2-buses with the 'Africa oil' buses.

**Comment by energyLS** [comment]
@Hazem-IEG do you have further information on how FT is implemented? At the last meeting we discussed that other technologies are just a “link”, but FT is apparently both a “bus” and a “link”. But we couldn't find any prove for that in https://github.com/PyPSA/pypsa-eur-sec/blob/master/scripts/prepare_sector_network.py at the first glance.

**Comment by Hazem-IEG** [comment]
Hey @energyLS, I will look into it now.. maybe that was an older version I got the network from. I'll be in touch shortly

**Comment by Hazem-IEG** [comment]
Okay, so this was changed in PyPSA-EUR-SEC v 0.5.0, 
see here https://pypsa-eur-sec.readthedocs.io/en/latest/release_notes.html#pypsa-eur-sec-0-4-0-11th-december-2020
Point no. 4 in the new features of the release

**Comment by energyLS** [comment]
Ah alright, thanks for investigating. So this is no longer an issue for us then, I guess?

**Comment by Hazem-IEG** [comment]
Not anymore, we'll take it further once we need to change it to a nodal representation. I'll close it.
