### ISSUE TITLE
Add missing demand sectors

### ISSUE THREAD

**Issue by Hazem-IEG** [pypsa-meets-africa/pypsa-earth-sec#37]
Missing demand sectors currently are:
- [x] H2 for shipping (Glen)
- [x] Land transport fuel cell (Leon)
- [x] land transport Fossil (Leon)
- [x] rename the power sector carrier to electricity (Glen)

**Comment by energyLS** [comment]
Land transport fossil was not added due to config settings. Nonetheless, the p_set parameter of the component load is set to 0 (default value), since there is no datetimeindex passed. I am currently investigating this error.

**Comment by davide-f** [comment]
I note here that with respect to PyPSA-Eur-Sec model, we may add also additional sectors.
At Earth scale, it may make sense to add also the water sector (desalination can play a big role in terms of energy consumption in some regions)
