### ISSUE TITLE
Get the solver to work

### ISSUE THREAD

**Issue by Hazem-IEG** [pypsa-meets-africa/pypsa-earth-sec#38]

**Comment by Hazem-IEG** [comment]
The solver currently produces the following error:

INFO:pypsa.opf:Performed preliminary steps
INFO:pypsa.opf:Building pyomo model using `kirchhoff` formulation
Traceback (most recent call last):

  File ~/projects/Github/pypsa-earth-sec/scripts/prepare_sector_network.py:917 in <module>
    n.lopf()

  File ~/anaconda3/envs/pypsa-africa/lib/python3.9/site-packages/pypsa/components.py:648 in lopf
    return network_lopf(self, **args)

  File ~/anaconda3/envs/pypsa-africa/lib/python3.9/site-packages/pypsa/opf.py:1653 in network_lopf
    network_lopf_build_model(network, snapshots, skip_pre=skip_pre,

  File ~/anaconda3/envs/pypsa-africa/lib/python3.9/site-packages/pypsa/opf.py:1461 in network_lopf_build_model
    define_nodal_balances(network,snapshots)

  File ~/anaconda3/envs/pypsa-africa/lib/python3.9/site-packages/pypsa/opf.py:1008 in define_nodal_balances
    efficiency = get_switchable_as_dense(network, 'Link', 'efficiency{}'.format(i), snapshots)

  File ~/anaconda3/envs/pypsa-africa/lib/python3.9/site-packages/pypsa/descriptors.py:163 in get_switchable_as_dense
    varying_i = pnl[attr].columns

KeyError: 'efficiency2'

**Comment by Hazem-IEG** [comment]
I managed to solve this in 9f629ef, the problem was that some of the attributes of the model needed to overridden before the network was solved.. that would add the missing `efficiency2` among others.

**Comment by energyLS** [comment]
Awesome, good work! Then we can close this issue once the branch is merged to main
