### ISSUE TITLE
Double check dummy data and order of magnitue

### ISSUE THREAD

**Issue by energyLS** [pypsa-meets-africa/pypsa-earth-sec#50]
Make sure the randomly generated dummy data makes sense and is not 1000 times smaller than the expected values

- [x] Energy_totals.csv (Leon)
- [x] industry sector (Hazem)
- [ ] transport_data (Davide)
- [ ] files in resources

**Comment by energyLS** [comment]
The values of the prenetwork look fine at the first glance:

![grafik](https://user-images.githubusercontent.com/89515385/159652321-bc6b1a37-5756-4ef2-9b6d-40a61c7e276b.png)

Further investigation of optimization results is required

**Comment by davide-f** [comment]
I've seen that the creation of the dummy data has been hard-coded inside the scripts.
I think it may be misleading; may it be better to modify the csv files and duplicate rows for missing countries? e.g. Morocco?

**Comment by Hazem-IEG** [comment]
I think this is a good idea. I've seen you already added Morocco

**Comment by energyLS** [comment]
I have checked Energy_totals.csv, the values are reasonable. 
And yes, makes sense to include Morocco in the csv instead of hard coding it :)
