### ISSUE TITLE
Model build crashes with a key error `'ES0 0'` in function `create_temperature_dummy`

### ISSUE THREAD

**Issue by energyLS** [pypsa-meets-africa/pypsa-earth-sec#67]
Description:
the model build crashes with a key error `'ES0 0'` in function `create_temperature_dummy` in the `helpers.py` script.  

Reason:
It crashes because the input data file ("resources/temp_air_total_elec_s_4.nc") has changed, previously it included the European dataset with the node 'ES0 0', but now we have the real data.

_Originally posted by @Hazem-IEG in https://github.com/pypsa-meets-africa/pypsa-earth-sec/issues/63#issuecomment-1081821594_

**Comment by davide-f** [comment]
#63 is ready, I think that it should solve this issue
