### ISSUE TITLE
Organize directories for (dummy) datasets

### ISSUE THREAD

**Issue by Hazem-IEG** [pypsa-meets-africa/pypsa-earth-sec#83]
First step is to make it easier for cleaning the repo, dummy datasets that are currently are to be placed in separate folder with a suffix in their name to be easily distinguishable. A rule to quickly copy the dummy data from their folder to resources shall also be added.

Further enhancement shall place the entire resources folder inside the data folder, to make it easier for new users and because it just makes sense :D 

- [x] place dummy datasets in a separate folder inside resources
- [x] create rule to automatically copy them to the resources folder
- [x] Reorganize directories to include resources inside data folder.

**Comment by davide-f** [comment]
Ready in #68
